1. Considere o conjunto de dados disponível em boston.csv, organizado em 14 colunas, sendo as 13 primeiras colunas os atributos e a  ́ultima coluna a saída. Os 13 atributos são usados na predição de preços de casas em Boston na década de 1970. Maiores detalhes sobre os dados podem ser conferidos em https://scikit-learn.org/stable/datasets/toy_dataset.html#boston-dataset.

(a) Aleatoriamente, divida o conjunto de dados em treino (80%) e teste (20%)<br>
(b) Treine 11 modelos de regress ̃ao polinomial, com ordens de 1 a 11.<br>
(c) Reporte o RMSE (raiz quadrada do erro quadr ́atico m ́edio) no treinamento e no teste para<br>
cada modelo. Fa ̧ca um gr ́afico para o treino e um gr ́afico para o teste.<br>
(d) Repita os 2 itens anteriores incluindo um termo de regulariza ̧c ̃ao L2 com fator λ = 0.01.<br>

In [5]:
import numpy as np
import matplotlib.pyplot as plt

### Importação dos dados

In [6]:
data = np.loadtxt('boston.csv', delimiter=',')
X = data[:, :-1]

In [7]:
print(X)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
